spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/control
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    open-in-view: false
    show-sql: true
  flyway:
    enabled: true